BOX_IMAGE = "ubuntu/trusty32"
NODE_COUNT = 4

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    add-apt-repository ppa:jonathonf/python-3.6
    apt-get update
    apt-get --yes install python3.6
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  config.ssh.forward_agent = true
  config.ssh.insert_key = true  
end
