# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "hashicorp/bionic64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "ansible"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
    config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y ansible
    SHELL
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y avahi-daemon libnss-mdns
  SHELL

  config.ssh.forward_agent = true
  config.ssh.insert_key = true  
end
