---
# tasks file for app-role
- include: install.yml
  tags: install

- name: copy info.php
  become: yes
  copy:
    src: info.php
    dest: /var/www/html/info.php
  notify:
    - restart apache  
  tags: config

