---
# tasks file for web-role
- name: install apache2
  become: yes
  apt:
    name: apache2
    state: present

- name: install php
  become: yes
  apt:
    name: php5
    state: present

- name: copy info.php
  become: yes
  copy:
    src: info.php
    dest: /var/www/html/info.php
  
